# Generated by Django 5.1.7 on 2025-09-09 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=225)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_funded_wallet', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('BYBIT', 'Bybit Email'), ('ON_CHAIN', 'On-Chain'), ('INTERNAL', 'Internal Transfer')], default='BANK_TRANSFER', max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('merchant_notified_at', models.DateTimeField(blank=True, null=True)),
                ('merchant_action_required', models.BooleanField(default=False)),
                ('network', models.CharField(blank=True, choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20'), ('BSC', 'BSC'), ('SOL', 'SOL')], max_length=50, null=True)),
                ('bybit_email', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_info', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit_notes', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('price_usd', models.FloatField(default=1e-05)),
                ('prev_price_usd', models.FloatField(default=0.0)),
                ('holders', models.IntegerField(default=0)),
                ('liquidity', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=1000000.0)),
                ('market_cap', models.CharField(default='$0', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('honey_pot', models.BooleanField(default=False)),
                ('highest_holder', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('price_updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in trending section')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('swap_back_amount', models.FloatField(default=0.0)),
                ('original_to_asset_price', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('swap_time', models.DateTimeField(help_text="In user's local timezone")),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_swaps', to='crypto_app.syntheticasset')),
                ('swap_back_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_swaps', to='crypto_app.syntheticasset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_swaps', to='crypto_app.syntheticasset')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_at_trade', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.syntheticasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_merchant', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('initial_deposit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('asset_a_balance', models.FloatField(default=0.0)),
                ('asset_b_balance', models.FloatField(default=0.0)),
                ('asset_c_balance', models.FloatField(default=0.0)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.TextField(blank=True, null=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_accounts', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('method', models.CharField(choices=[('INTERNAL', 'Internal Transfer'), ('BYBIT', 'Bybit Email'), ('ON_CHAIN', 'On-Chain'), ('BANK', 'Bank Transfer')], default='INTERNAL', max_length=255)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('chain', models.CharField(blank=True, max_length=50, null=True)),
                ('user_confirmation_required', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_notes', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_buttons', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('firebase_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crypto_app.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('swap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_app.swaprequest')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_app.withdrawal')),
            ],
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='unique_user_token')],
            },
        ),
        migrations.CreateModel(
            name='CandlestickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('interval', models.CharField(default='1min', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candlestick_data', to='crypto_app.syntheticasset')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='crypto_app__asset_i_f76f69_idx'), models.Index(fields=['asset', 'interval', 'timestamp'], name='crypto_app__asset_i_aa1a81_idx')],
                'unique_together': {('asset', 'timestamp', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.syntheticasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset')},
            },
        ),
    ]
